version: '3.8'
services:
  api:
    build: .
    ports:
      - "${PORT-3333}:3333"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    depends_on:
      mongo:
        condition: service_started
      neo4j:
        condition: service_healthy

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=${NEO4J_USER-neo4j}/${NEO4J_PASSWORD-neo4j_password}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:7474/ || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mongo_data:
  neo4j_data: